<a href="https://colab.research.google.com/github/Vitela-debug/Colab_S1_Clase-de-progralaci-n_273522_TVB/blob/main/S06_Actividad_01_NumPy_273522.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Sesión 06 — Actividad calificable: NumPy y preparación de datos

# Actividad calificada — NumPy y preparación de datos

**Programación para Analítica Descriptiva y Predictiva**

Maestría en Inteligencia Artificial y Analítica de Datos — UACJ

---


**Nombre completo: Tania Vitela Barraza**  
**Matrícula: 273522**  

---

**Entrega:** individual, en este notebook de Google Colab (comparte el enlace con permiso de edición para el docente).
**Plazo:** 7 días naturales a partir de la publicación de esta actividad.
**Penalización por entrega tardía:** 5% por día, hasta 7 días; después de eso, la actividad no se recibe.
**Valor total:** 100 puntos.

### Herramientas permitidas

Esta actividad evalúa lo visto hasta la Sesión 6: expresiones regulares (`re`), comprensión de listas, `map()`, `lambda`, y NumPy. **No uses pandas ni scikit-learn** — todavía no se han visto en el curso, y su uso no sumará puntos aunque el resultado sea correcto.

### Cómo se evalúa

Cada ejercicio indica su valor en puntos. Se evalúa el resultado correcto **y** el uso apropiado de las herramientas indicadas en cada enunciado — una solución correcta que ignore la herramienta pedida (por ejemplo, usar un bucle `for` donde se pide `map()` o una operación vectorizada) no obtiene el puntaje completo. Comenta tu código donde el paso no sea evidente.

## Librerías

Ejecuta esta celda antes de empezar.

In [11]:
import re
import numpy as np

## Datos de partida

Una red de 4 estaciones meteorológicas registró temperatura y humedad durante 5 días. Los datos llegaron en un formato de texto crudo, como ocurre frecuentemente al recibir información de sensores o sistemas externos. Ejecuta la siguiente celda para cargar las lecturas — **no la modifiques**.

In [12]:
lecturas_crudas = [
    "EST-01 | Dia1 | Temp: 22.3C | Hum: 60%",
    "EST-01 | Dia2 | Temp: 19.8C | Hum: 64%",
    "EST-01 | Dia3 | Temp: 24.1C | Hum: 58%",
    "EST-01 | Dia4 | Temp: 26.5C | Hum: 55%",
    "EST-01 | Dia5 | Temp: 21.0C | Hum: 63%",
    "EST-02 | Dia1 | Temp: 24.0C | Hum: 70%",
    "EST-02 | Dia2 | Temp: 23.5C | Hum: 72%",
    "EST-02 | Dia3 | Temp: 27.2C | Hum: 65%",
    "EST-02 | Dia4 | Temp: 20.1C | Hum: 74%",
    "EST-02 | Dia5 | Temp: 22.8C | Hum: 69%",
    "EST-03 | Dia1 | Temp: 18.5C | Hum: 80%",
    "EST-03 | Dia2 | Temp: 19.2C | Hum: 78%",
    "EST-03 | Dia3 | Temp: 20.0C | Hum: 77%",
    "EST-03 | Dia4 | Temp: 21.5C | Hum: 75%",
    "EST-03 | Dia5 | Temp: 19.9C | Hum: 79%",
    "EST-04 | Dia1 | Temp: 27.8C | Hum: 50%",
    "EST-04 | Dia2 | Temp: 26.3C | Hum: 52%",
    "EST-04 | Dia3 | Temp: 25.9C | Hum: 53%",
    "EST-04 | Dia4 | Temp: 24.0C | Hum: 56%",
    "EST-04 | Dia5 | Temp: 28.1C | Hum: 49%",
]

print(len(lecturas_crudas), "lecturas cargadas")
print(lecturas_crudas[0])

20 lecturas cargadas
EST-01 | Dia1 | Temp: 22.3C | Hum: 60%


---

## Ejercicio 1 — Extracción con expresiones regulares (10 pts)

Usando `re` y comprensión de listas, extrae de cada cadena en `lecturas_crudas` el identificador de estación (por ejemplo `'EST-01'`) y el valor de temperatura como texto (por ejemplo `'22.3'`, sin la `C`). El resultado debe ser una lista de tuplas `(estacion, temperatura_texto)`, en el mismo orden que `lecturas_crudas`.

*Por qué importa: en la práctica, los datos casi nunca llegan ya estructurados — extraerlos de texto libre es el primer paso de cualquier pipeline de análisis.*

In [13]:
# Tu código aquí
extraidos = [(re.search(r'EST-\d+', lectura).group(), re.search(r'Temp:\s*([\d.]+)C', lectura).group(1)) #\d+ Busca uno o mas digitos, \s* para cero o más espacios, .]+) punto decimal y mas caracteres
    for lectura in lecturas_crudas] #para la lista de compresion
print(extraidos)
print(len(extraidos))
print(type(extraidos))
print(type(extraidos[0]))

[('EST-01', '22.3'), ('EST-01', '19.8'), ('EST-01', '24.1'), ('EST-01', '26.5'), ('EST-01', '21.0'), ('EST-02', '24.0'), ('EST-02', '23.5'), ('EST-02', '27.2'), ('EST-02', '20.1'), ('EST-02', '22.8'), ('EST-03', '18.5'), ('EST-03', '19.2'), ('EST-03', '20.0'), ('EST-03', '21.5'), ('EST-03', '19.9'), ('EST-04', '27.8'), ('EST-04', '26.3'), ('EST-04', '25.9'), ('EST-04', '24.0'), ('EST-04', '28.1')]
20
<class 'list'>
<class 'tuple'>


---

## Ejercicio 2 — Construcción del arreglo numérico (10 pts)

A partir de las temperaturas extraídas en el Ejercicio 1 (que están en texto), usa `map()` junto con una conversión a `float` para construir un `ndarray` de tipo numérico. Verifica e imprime su `dtype`.

*Por qué importa: conectar la extracción de texto con un tipo de dato numérico utilizable es un paso que se repite constantemente al preparar datos.*

In [14]:
# Tu código aquí
temperaturas = np.array(list(map(lambda x: float(x[1]), extraidos))) #map como iterador y lo convertimos a lista para luego comvertirlo en array

print(temperaturas)
print(temperaturas.dtype)


[22.3 19.8 24.1 26.5 21.  24.  23.5 27.2 20.1 22.8 18.5 19.2 20.  21.5
 19.9 27.8 26.3 25.9 24.  28.1]
float64


---

## Ejercicio 3 — Organización en una matriz 2D (10 pts)

Reorganiza el arreglo de temperaturas del Ejercicio 2 en una matriz de 4 filas (una por estación) × 5 columnas (una por día) usando `reshape()`. Los datos ya están ordenados por estación en `lecturas_crudas`, así que no necesitas reordenarlos manualmente. Reporta `shape`, `ndim`, `size` y `dtype` de la matriz resultante.

In [15]:
# Tu código aquí
matriz_temp = temperaturas.reshape(4,5)
print(matriz_temp)
print("Estructura",matriz_temp.shape)
print("Dimension", matriz_temp.ndim)
print("Tamano", matriz_temp.size)
print("Tipo", matriz_temp.dtype)

[[22.3 19.8 24.1 26.5 21. ]
 [24.  23.5 27.2 20.1 22.8]
 [18.5 19.2 20.  21.5 19.9]
 [27.8 26.3 25.9 24.  28.1]]
Estructura (4, 5)
Dimension 2
Tamano 20
Tipo float64


---

## Ejercicio 4 — Indexado, slicing y transposición (10 pts)

A partir de `matriz_temp`:

1. Extrae la fila completa correspondiente a `EST-03`.
2. Extrae la columna completa correspondiente al Día 4.
3. Extrae la submatriz de las primeras 2 estaciones durante los primeros 3 días.
4. Transpón la matriz con `.T` e imprime su nueva forma (`shape`). En una celda de texto (Markdown) o un comentario, explica en qué situación tendría sentido trabajar con los días como filas y las estaciones como columnas.

In [16]:
# Tu código aquí
fila_est03 = matriz_temp[2]
print("1. EST-03:",fila_est03)
columna_dia4 = matriz_temp[:,3]
print("2. Día 4:",columna_dia4)
submatriz = matriz_temp[0:2,0:3]
print("3. Submatriz:",submatriz)
tans_matriz_temp = matriz_temp.T
print("4. Matriz transpuesta:",tans_matriz_temp)
print("4. Nueva forma:",tans_matriz_temp.shape)


1. EST-03: [18.5 19.2 20.  21.5 19.9]
2. Día 4: [26.5 20.1 21.5 24. ]
3. Submatriz: [[22.3 19.8 24.1]
 [24.  23.5 27.2]]
4. Matriz transpuesta: [[22.3 24.  18.5 27.8]
 [19.8 23.5 19.2 26.3]
 [24.1 27.2 20.  25.9]
 [26.5 20.1 21.5 24. ]
 [21.  22.8 19.9 28.1]]
4. Nueva forma: (5, 4)


**En qué situación tendría sentido trabajar con los días como filas y las estaciones como columnas?**


Trabajar con los días como filas y las estaciones como columnas tiene sentido cuando queremos comparar las estaciones para cada día, python tine muchas funciones que se pueden hacer tanto en filas
ESTACIONES × DÍAS
puede ser más cómodo si normalmente se analiza cada estación
Mientras que:
DÍAS × ESTACIONES
puede ser más cómodo si normalmente se analiza cada día.

---

## Ejercicio 5 — Máscaras booleanas, verificación y fancy indexing (15 pts)

1. Usa una máscara booleana sobre `matriz_temp` para identificar qué lecturas superan los 25°C.
2. Usando `any()`, verifica si **alguna** estación tuvo, en algún día, una lectura mayor a 25°C.
3. Usando `all()`, verifica si la estación `EST-04` (fila correspondiente) tuvo **todos** sus días por encima de los 24°C.
4. Usando fancy indexing, reordena las filas de `matriz_temp` según la lista de prioridad `[2, 0, 3, 1]` (es decir, primero EST-03, luego EST-01, EST-04 y EST-02).

*Por qué importa: filtrar por condición, verificar rápidamente supuestos sobre los datos, y reordenar según un criterio externo son operaciones cotidianas al priorizar qué datos revisar primero.*

In [17]:
# Tu código aquí
mascara = matriz_temp > 25
print("1. Mascara", mascara)
any_mascara = np.any(matriz_temp > 25)
print("2. Any", any_mascara)
all_mascara = np.all(matriz_temp[3] > 24)
print("3. All", all_mascara)
fancy_indexing = matriz_temp[[2,0,3,1]]
print("4. Fancy indexing", fancy_indexing)

1. Mascara [[False False False  True False]
 [False False  True False False]
 [False False False False False]
 [ True  True  True False  True]]
2. Any True
3. All False
4. Fancy indexing [[18.5 19.2 20.  21.5 19.9]
 [22.3 19.8 24.1 26.5 21. ]
 [27.8 26.3 25.9 24.  28.1]
 [24.  23.5 27.2 20.1 22.8]]


---

## Ejercicio 6 — Broadcasting y `np.where()` (15 pts)

Cada estación tiene un descalibre de sensor conocido, dado por este arreglo (en el mismo orden que las filas de `matriz_temp`: EST-01, EST-02, EST-03, EST-04):

```python
descalibre = np.array([-0.5, 1.2, 0.0, -1.0])
```

1. Usa broadcasting para aplicar la corrección correspondiente a cada fila de `matriz_temp` (cada estación se ajusta con su propio valor de `descalibre`). Guarda el resultado en una variable nueva, por ejemplo `matriz_corregida`. **Pista:** si intentas sumar `matriz_temp + descalibre` directamente obtendrás un error de formas incompatibles — el broadcasting solo funciona si `descalibre` tiene la forma `(4, 1)` en lugar de `(4,)`, para que cada valor se alinee con una fila completa. Usa `reshape()` (ya lo conoces del Bloque 2) para darle esa forma antes de sumar.
2. Sobre `matriz_corregida`, usa `np.where()` para generar una matriz paralela de etiquetas de texto: `'alta'` si la lectura corregida supera los 25°C, `'normal'` en caso contrario.

In [18]:
descalibre = np.array([-0.5, 1.2, 0.0, -1.0])

# Tu código aquí
matriz_corregida = matriz_temp + descalibre.reshape(4,1)
print("1. Matriz corregida", matriz_corregida)
etiquetas = np.where(matriz_corregida > 25, 'alta', 'normal')
print("2. Etiquetas", etiquetas)


1. Matriz corregida [[21.8 19.3 23.6 26.  20.5]
 [25.2 24.7 28.4 21.3 24. ]
 [18.5 19.2 20.  21.5 19.9]
 [26.8 25.3 24.9 23.  27.1]]
2. Etiquetas [['normal' 'normal' 'normal' 'alta' 'normal']
 ['alta' 'normal' 'alta' 'normal' 'normal']
 ['normal' 'normal' 'normal' 'normal' 'normal']
 ['alta' 'alta' 'normal' 'normal' 'alta']]


---

## Ejercicio 7 — Agregaciones por eje (15 pts)

Usando `matriz_corregida` del Ejercicio 6:

1. Calcula el promedio y la desviación estándar de temperatura **por estación** (usa el `axis` correspondiente).
2. Calcula el promedio de temperatura **por día** (usa el `axis` correspondiente).
3. Sin usar funciones no vistas en el curso (por ejemplo, sin `argmax`), determina **qué día** tuvo el promedio más alto entre estaciones. Sugerencia: obtén el valor máximo de los promedios por día con `.max()`, y compáralo con el arreglo de promedios por día usando `==` para generar una máscara booleana — la posición con `True` te dice qué día fue.

In [19]:
# Tu código aquí
promedio_estacion = np.mean(matriz_corregida, axis=1)
desviacion_estacion = np.std(matriz_corregida, axis=1)
print("1. Promedio por estación", promedio_estacion,"Desviación estandar por estación", desviacion_estacion)

promedio_dia = np.mean(matriz_corregida, axis=0)
desviacion_dia = np.std(matriz_corregida, axis=0)
print("2. Promedio por día", promedio_dia,"Desviación estandar por día", desviacion_dia)

prom_max= promedio_dia.max()
macara_prom = promedio_dia == prom_max
print("3. Arreglo de día con promedio más alto", macara_prom)
print(" Día con promedio más alto", np.where(macara_prom)[0][0] + 1) #Primer elemento de la tupla true y +1 para sumar la posion de pyton que empieza en 0


1. Promedio por estación [22.24 24.72 19.82 25.42] Desviación estandar por estación [2.36016949 2.27982455 0.99879928 1.4743134 ]
2. Promedio por día [23.075 22.125 24.225 22.95  22.875] Desviación estandar por día [3.19951168 2.88303226 3.0053078  1.87949461 2.8985988 ]
3. Arreglo de día con promedio más alto [False False  True False False]
 Día con promedio más alto 3


---

## Ejercicio 8 — Síntesis: resumen por estación (15 pts)

Usando `map()` y/o comprensión de listas, genera una lista de cadenas de resumen, una por estación, que combine:

- El identificador de estación extraído en el Ejercicio 1.
- El promedio de temperatura corregida de esa estación (Ejercicio 7), formateado a un decimal.
- Su clasificación predominante (`'alta'` o `'normal'`) — usa `np.unique()` sobre las etiquetas de esa estación (del Ejercicio 6) para encontrar cuál aparece con mayor frecuencia entre las dos.

Formato esperado por cadena: `"EST-01: 23.4°C promedio — clasificación predominante: normal"`

Finalmente, ordena la lista de resúmenes de mayor a menor promedio de temperatura usando `sorted()` con `key` y `lambda` (como en la Sesión 4/5), e imprime el resultado ordenado.

In [20]:
# Tu código aquí


# Extraer estación y temperatura (Ejercicio 1)
extraidos = [(re.search(r'EST-\d+', lectura).group(), re.search(r'Temp:\s*([\d.]+)C', lectura).group(1)) #\d+ Busca uno o mas digitos, \s* para cero o más espacios, .]+) punto decimal y mas caracteres
    for lectura in lecturas_crudas] #para la lista de compresion

# Matriz corregida (Ejercicio 6)
matriz_corregida = matriz_temp + descalibre.reshape(4, 1)

# Clasificación (Ejercicioo 6)
etiquetas = np.where(matriz_corregida > 25, 'alta', 'normal')

# Promedio por estación (Ejercicio 7)
promedio_estacion = np.mean(matriz_corregida, axis=1)

# Obtener los identificadores de estación sin repetir
estaciones = list(dict.fromkeys([dato[0] for dato in extraidos])) #Se usa la comprension de lista para solo tomar el primer valor de la tupla ('Est-01,'23') de extraidos

# Crear resumen que luego se ordenara
resumenes = []

for i, estacion in enumerate(estaciones):
    etiquetas_estacion = etiquetas[i] # Etiquetas de la estación
    valores, frecuencias = np.unique(etiquetas_estacion,return_counts=True) # Verifica cuántas veces aparece 'alta' y 'normal' en la estación
    clasificacion_predominante = valores[frecuencias == frecuencias.max()][0] # Busca la clasificación que tiene la frecuencia más alta y guarda como la clasificación predominante
    resumen = (f"{estacion}: {promedio_estacion[i]:.1f}°C promedio — "f"clasificación predominante: {clasificacion_predominante}") #Genera el resumen de lo que se obtuvo anteriormente (:.1f formato de número decimal (float) una cifra despues del punto)
    resumenes.append(resumen)

# Ordenar de mayor a menor promedio
resumenes_ordenados = sorted(resumenes, key=lambda x: float(x.split(": ")[1].split("°C")[0]),reverse=True)

print(resumenes_ordenados)

['EST-04: 25.4°C promedio — clasificación predominante: alta', 'EST-02: 24.7°C promedio — clasificación predominante: normal', 'EST-01: 22.2°C promedio — clasificación predominante: normal', 'EST-03: 19.8°C promedio — clasificación predominante: normal']


---

## Antes de entregar

- Verifica que el notebook completo corra de principio a fin sin errores (**Entorno de ejecución → Ejecutar todas**).
- Confirma que no usaste pandas ni scikit-learn.
- Comparte el notebook con permiso de **edición** para el docente.
- Revisa que tu nombre y número de control estén en la primera celda.